# Generated by Django 5.2.6 on 2025-09-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='homepage_services/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Homepage Service',
                'verbose_name_plural': 'Homepage Services',
                'ordering': ['-created_at'],
            },
        ),
    ]
