# Generated by Django 5.2.6 on 2025-09-30 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_homepageservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Testimonials Section',
                'verbose_name_plural': 'Testimonials Section',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_text', models.CharField(help_text='Short text under name (e.g., designation)', max_length=200)),
                ('testimonial_text', models.TextField()),
                ('profile_image', models.ImageField(upload_to='testimonials/')),
                ('stars', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='bookings.testimonialsection')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
