# Generated by Django 5.2.6 on 2025-10-01 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_servicecategory_whychooseus_serviceitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=200)),
                ('main_text', models.TextField()),
                ('section2_image', models.ImageField(upload_to='about/')),
                ('section2_title', models.CharField(max_length=200)),
                ('section2_text', models.TextField()),
                ('section3_title', models.CharField(max_length=200)),
                ('section3_text', models.TextField()),
                ('section3_image', models.ImageField(upload_to='about/')),
                ('section4_image', models.ImageField(upload_to='about/')),
                ('section4_title', models.CharField(max_length=200)),
                ('section4_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItemBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='item-banners/')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='bookings.serviceitem')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reviews', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service-entries/')),
                ('order', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_entries', to='bookings.serviceitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
