# Generated by Django 5.2.6 on 2025-10-02 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_emergencycontact_emergencypage_emergencyfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contactinfoblock',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_blocks', to='bookings.contactpage'),
        ),
        migrations.AlterField(
            model_name='contactinfoblock',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='contact_icons/'),
        ),
    ]
